In [1]:
# import the data
# sep x,y
# find out the coef , intercept
# y = m1*x1 + m2*x2 + m3*x3 + c
# lr.predict([[12,20,32]])
# calculate r2_score

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('supershop.csv')

In [4]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
df.Area=le.fit_transform(df.Area)

In [7]:
df.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [8]:
df.shape

(50, 5)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Marketing Spend  50 non-null     float64
 1   Administration   50 non-null     float64
 2   Transport        49 non-null     float64
 3   Area             50 non-null     int32  
 4   Profit           50 non-null     float64
dtypes: float64(4), int32(1)
memory usage: 1.9 KB


In [10]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          1
Area               0
Profit             0
dtype: int64

In [11]:
df1=df.copy()

In [12]:
df1.Transport=df1.Transport.fillna(df1.Transport.mean())

In [13]:
df1.Transport.mean()

215331.73244897963

In [14]:
df1.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

# MinMax Scaling

In [15]:
from sklearn.preprocessing import MinMaxScaler
mminmax=MinMaxScaler()

In [16]:
df1[['Marketing Spend','Administration','Transport','Area','Profit']]=mminmax.fit_transform(df1[['Marketing Spend','Administration','Transport','Area','Profit']])

In [17]:
df1.head()

Marketing Spend  Administration  Transport  Area    Profit
0         0.692617        0.651744   1.000000   0.5  1.000000
1         0.983359        0.761972   0.940893   0.0  0.997355
2         0.927985        0.379579   0.864664   1.0  0.993178
3         0.873136        0.512998   0.812235   0.5  0.947292
4         0.859438        0.305328   0.776136   1.0  0.853171

# Linear Regression using Gradient Decent

In [18]:
#x=df1[['Marketing Spend','Administration','Transport','Area' ]]
x1=df1['Marketing Spend']
y1=df1['Profit']

In [19]:
x1.head()

0    0.692617
1    0.983359
2    0.927985
3    0.873136
4    0.859438
Name: Marketing Spend, dtype: float64

In [20]:
x1.shape

(50,)

In [21]:
y1.head()

0    1.000000
1    0.997355
2    0.993178
3    0.947292
4    0.853171
Name: Profit, dtype: float64

In [22]:
y1.shape

(50,)

In [23]:
n=len(x1)

In [24]:
n

50

In [25]:
m1 = 0
c = 0
l = 0.0001

n = int(len(x1))
iteration = 20

#loop
for i in range(iteration):
    predy = (m1*x1) + c
    der_m1 = (-2/n) * sum(x1*(y1-predy))
    der_c1 = (-2/n) * sum(y1-predy)
    
    m1 = (m1 - ( l * der_m1))
    c = (c - (l * der_c1))
    
    print(m1,c)

6.045781639459789e-05 0.00010961933046338498
0.00012090254109853657 0.0002192113459878444
0.00018133417726574967 0.00032877605320376287
0.0002417527280494066 0.00043831345873991754
0.0003021581966019126 0.0005478235692234787
0.0003625505860749091 0.0006573063912800101
0.00042292989961927366 0.0007667619315334694
0.00048329614038512055 0.0008761901966062084
0.0005436493115218005 0.0009855911931189736
0.0006039894161779013 0.0010949649276909064
0.0006643164575012474 0.001204311406939544
0.0007246304386389007 0.0013136306374808187
0.0007849313627371605 0.0014229226259290595
0.0008452192329415637 0.001532187378896992
0.000905494052396885 0.0016414249029957386
0.0009657558242471368 0.001750635204834819
0.00102600455163557 0.0018598182910221507
0.0010862402377046735 0.0019689741681640496
0.001146462885596175 0.0020781028428652295
0.0012066724984510404 0.0021872043217288036


In [26]:
x2=df1['Administration']
y2=df1['Profit']

In [27]:
x2.head()

0    0.651744
1    0.761972
2    0.379579
3    0.512998
4    0.305328
Name: Administration, dtype: float64

In [28]:
y2.head()

0    1.000000
1    0.997355
2    0.993178
3    0.947292
4    0.853171
Name: Profit, dtype: float64

In [29]:
n=len(x2)

In [30]:
n

50

In [31]:
m2 = 0
c = 0
l = 0.0001

n = int(len(x2))
iteration = 20

#loop
for i in range(iteration):
    predy = (m2*x2) + c
    der_m2 = (-2/n) * sum(x2*(y2-predy))
    der_c2 = (-2/n) * sum(y2-predy)
    
    m2 = (m2 - ( l * der_m2))
    c = (c - (l * der_c2))
    
    print(m2,c)

6.036942021684325e-05 0.00010961933046338498
0.00012072317467878908 0.00021921029751410012
0.00018106126744226107 0.00032877290849587864
0.0002413837025626326 0.00043830717075055224
0.00030169048409422686 0.0005478130916180518
0.0003619816160903174 0.0006572906784364076
0.0004222571026031284 0.0007667399385417499
0.0004825169476838346 0.0008761608792683096
0.0005427611553825621 0.0009855535079484187
0.0006029897297483879 0.0010949178319125106
0.0006632026748293411 0.0012042538584891207
0.0007233999946724023 0.001313561595004887
0.0007835816933235045 0.0014228410487845502
0.000843747774827533 0.0015320922271509548
0.0009038982432283258 0.0016413151374250492
0.0009640331025686739 0.0017505097869258861
0.0010241523568903215 0.0018596761829706235
0.0010842560102339665 0.001968814332874524
0.0011443440666392603 0.0020779242439509576
0.0012044165301448085 0.002187005923511399


In [32]:
x3=df1['Transport']
y3=df1['Profit']

In [33]:
x3.head()

0    1.000000
1    0.940893
2    0.864664
3    0.812235
4    0.776136
Name: Transport, dtype: float64

In [34]:
y3.head()

0    1.000000
1    0.997355
2    0.993178
3    0.947292
4    0.853171
Name: Profit, dtype: float64

In [35]:
n=len(x3)

In [36]:
n

50

In [37]:
m3 = 0
c = 0
l = 0.0001

n = int(len(x3))
iteration = 20

#loop
for i in range(iteration):
    predy = (m3*x3) + c
    der_m3 = (-2/n) * sum(x3*(y2-predy))
    der_c3 = (-2/n) * sum(y3-predy)
    
    m3 = (m3 - ( l * der_m3))
    c = (c - (l * der_c3))
    
    print(m3, c)

5.876590029096527e-05 0.00010961933046338498
0.00011751861977478973 0.00021921137267339987
0.00017625816165443267 0.00032877613329089235
0.0002349845291320724 0.00043831361897508556
0.0002936977254091063 0.0005478238363835784
0.0003523977536861512 0.0006573067921723461
0.0004110846171630433 0.0007667624929957405
0.0004697583190388388 0.0008761909455064906
0.0005284188625118134 0.0009855921563557025
0.0005870662507794633 0.0010949661321928603
0.0006457004870385047 0.0012043128796658266
0.0007043215744848745 0.0013136324054208424
0.0007629295163137302 0.0014229247161025274
0.0008215243157194502 0.0015321898183538814
0.0008801059758956337 0.0016414277188162832
0.0009386745000351015 0.0017506384241294925
0.0009972298913298954 0.001859821940931649
0.0010557721529712795 0.001968978275859274
0.001114301288149739 0.0020781074355472697
0.0011728173000549813 0.0021872094266289204


In [38]:
x4=df1['Area']
y4=df1['Profit']

In [39]:
x4.head()

0    0.5
1    0.0
2    1.0
3    0.5
4    1.0
Name: Area, dtype: float64

In [40]:
y4.head()

0    1.000000
1    0.997355
2    0.993178
3    0.947292
4    0.853171
Name: Profit, dtype: float64

In [41]:
n=len(x4)

In [42]:
n

50

In [43]:
m4 = 0
c = 0
l = 0.0001

n = int(len(x4))
iteration = 20

#loop
for i in range(iteration):
    predy = (m4*x4) + c
    der_m4 = (-2/n) * sum(x4*(y4-predy))
    der_c4 = (-2/n) * sum(y4-predy)
    
    m4 = (m4 - ( l * der_m4))
    c = (c - (l * der_c4))
    
    print(m4,c)

5.648414940767968e-05 0.00010961933046338498
0.00011295298090487191 0.00021921120161403528
0.0001694064984233401 0.00032877562044496874
0.0002258447058938439 0.0004383125939474193
0.00028226760724613933 0.0005478221291108371
0.0003386752064089792 0.0006573042329228899
0.0003950675073101133 0.0007667589123694622
0.0004514445138762886 0.0008761861744346569
0.0005078062300332497 0.000985586026100795
0.0005641526597057388 0.0010949584743484165
0.0006204838068174961 0.0012043035261562805
0.0006767996752912601 0.001313621188501366
0.0007331002690487681 0.001422911468358872
0.0007893855920107556 0.0015321743727022186
0.0008456556480969576 0.0016414099085030462
0.0009019104412261081 0.001750618082731217
0.0009581499753159408 0.0018597989023548156
0.001014374254283189 0.0019689523743401487
0.0010705832820435866 0.002078078505651746
0.0011267770625118668 0.00218717730325236


In [44]:
m1 =6.0457816394597874e-05  
m2 = 6.036942021684325e-05 
m3 = 5.876590029096527e-05 
m4 = 5.6484149407679686e-05 

x1=0.692617
x2=0.651744
x3=1.000000
x4=0.5


c = 1.625906503657531e-05



y = m1*x1+m2*x2+m3*x3+m4*x4+c
y

0.00018448655885896392

In [45]:
x=df1.drop(['Profit'],axis=1)
y=df1['Profit']

In [46]:
x.head()

Marketing Spend  Administration  Transport  Area
0         0.692617        0.651744   1.000000   0.5
1         0.983359        0.761972   0.940893   0.0
2         0.927985        0.379579   0.864664   1.0
3         0.873136        0.512998   0.812235   0.5
4         0.859438        0.305328   0.776136   1.0

In [47]:
y.head()

0    1.000000
1    0.997355
2    0.993178
3    0.947292
4    0.853171
Name: Profit, dtype: float64

# Ordinary Least Squares

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
lr = LinearRegression()

In [50]:
lr.fit(df1.drop(['Profit'],axis=1), df['Profit'])

LinearRegression()

In [51]:
lr.predict([[0.692617,0.651744,1.000000,0.5]])

C:\Users\Runa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([160383.97326471])

In [52]:
lr.predict([[1.000000,0.997355,0.993178,0.947292]])

C:\Users\Runa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([195265.72451605])

In [53]:
lr.intercept_

43578.236861032376

In [54]:
lr.coef_

array([111286.00953079,   4169.78952313,  37580.09700602,  -1141.15593698])

In [55]:
Y_pred = lr.predict(df1.drop(['Profit'],axis=1))

In [56]:
from sklearn.metrics import r2_score
Score = r2_score(df[['Profit']], Y_pred)

In [57]:
Score

0.9046207720419526

In [58]:
lr.score(df1.drop(['Profit'],axis=1) , df[['Profit']])

0.9046207720419526